apiVersion: v1
kind: PersistentVolume
metadata:
  name: <volume-name>
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: <storage-size>
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "<host-path>"
