apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <claim-name>
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: <storage-size>

