apiVersion: v1
kind: Service
metadata:
  name: <service-name>
spec:
  selector:
    app: <app-label>
  ports:
    - protocol: TCP
      port: <port>
      targetPort: <target-port>
  type: LoadBalancer
